### ISSUE TITLE
Fix test papers.tests.paper.TestPaperWithReviewsView

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#140]
This test fails with the following error

```
FAIL: test_queries_anonymous (openreview.apps.papers.tests.paper.TestPaperWithReviewsView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willem/code/open-review/openreview/apps/papers/tests/paper.py", line 19, in test_queries_anonymous
    self.client.get(reverse("paper", args=[self.paper.id]))
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/willem/code/open-review/openreview/apps/tools/testing.py", line 286, in assert_max_queries
    raise AssertionError(msg)
AssertionError: Should take at most 8 queries, but took 12.
[0] SELECT "main_paper"."id", "main_paper"."doc_id", "main_paper"."title", "main_paper"."abstract", "main_paper"."publisher", "main_paper"."publish_date", "main_paper"."urls" FROM "main_paper" WHERE "main_paper"."id" = 70  (0.000)
[1] SELECT ("main_paper_authors"."paper_id") AS "_prefetch_related_val_paper_id", "main_author"."id", "main_author"."user_id", "main_author"."name" FROM "main_author" INNER JOIN "main_paper_authors" ON ( "main_author"."id" = "main_paper_authors"."author_id" ) WHERE "main_paper_authors"."paper_id" IN (70) (0.001)
[2] SELECT ("main_paper_keywords"."paper_id") AS "_prefetch_related_val_paper_id", "main_keyword"."id", "main_keyword"."label" FROM "main_keyword" INNER JOIN "main_paper_keywords" ON ( "main_keyword"."id" = "main_paper_keywords"."keyword_id" ) WHERE "main_paper_keywords"."paper_id" IN (70) (0.000)
[3] SELECT ("main_paper_categories"."paper_id") AS "_prefetch_related_val_paper_id", "main_category"."id", "main_category"."name", "main_category"."arxiv_code", "main_category"."parent_id" FROM "main_category" INNER JOIN "main_paper_categories" ON ( "main_category"."id" = "main_paper_categories"."category_id" ) WHERE "main_paper_categories"."paper_id" IN (70) (0.001)
[4] SELECT "main_review"."id", "main_review"."text", "main_review"."rating", "main_review"."timestamp", "main_review"."poster_id", "main_review"."paper_id", "main_review"."parent_id", "main_review"."anonymous", "main_review"."external" FROM "main_review" WHERE ("main_review"."paper_id" = 70  AND "main_review"."parent_id" IS NULL) LIMIT 1 (0.000)
[5] SELECT "main_review"."id", "main_review"."text", "main_review"."rating", "main_review"."timestamp", "main_review"."poster_id", "main_review"."paper_id", "main_review"."parent_id", "main_review"."anonymous", "main_review"."external", "accounts_user"."id", "accounts_user"."password", "accounts_user"."last_login", "accounts_user"."is_superuser", "accounts_user"."username", "accounts_user"."first_name", "accounts_user"."last_name", "accounts_user"."email", "accounts_user"."is_staff", "accounts_user"."is_active", "accounts_user"."date_joined", "accounts_user"."title", "accounts_user"."university", "accounts_user"."votes_public" FROM "main_review" LEFT OUTER JOIN "accounts_user" ON ( "main_review"."poster_id" = "accounts_user"."id" ) WHERE "main_review"."paper_id" = 70  (0.001)
[6] SELECT "main_vote"."review_id", SUM("main_vote"."vote") AS "n" FROM "main_vote" WHERE ("main_vote"."review_id" IN (104, 105) AND "main_vote"."vote" > 0 ) GROUP BY "main_vote"."review_id" (0.001)
[7] SELECT "main_vote"."review_id", SUM("main_vote"."vote") AS "n" FROM "main_vote" WHERE ("main_vote"."review_id" IN (104, 105) AND "main_vote"."vote" < 0 ) GROUP BY "main_vote"."review_id" (0.000)
[8] SELECT SUM("main_vote"."vote") AS "n" FROM "main_vote" WHERE ("main_vote"."review_id" = 106  AND "main_vote"."vote" > 0 ) (0.000)
[9] SELECT SUM("main_vote"."vote") AS "n" FROM "main_vote" WHERE ("main_vote"."review_id" = 106  AND "main_vote"."vote" < 0 ) (0.000)
[10] SELECT SUM("main_vote"."vote") AS "n" FROM "main_vote" WHERE ("main_vote"."review_id" = 107  AND "main_vote"."vote" > 0 ) (0.000)
[11] SELECT SUM("main_vote"."vote") AS "n" FROM "main_vote" WHERE ("main_vote"."review_id" = 107  AND "main_vote"."vote" < 0 ) (0.000)

```

Remember to document all affected code (including the test itself)!

Please create a branch from 'base-design' and don't merge before code is approved by Martijn (and possibly Thomas)

**Comment by martijnbastiaan** [comment]
Fixed in earlier commit!
